[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = ['@openzeppelin/contracts=lib/openzeppelin-contracts/contracts']
[rpc_endpoints]
buildbear = "https://rpc.buildbear.io/sanam"
[profile.sourcify]
url= "https://rpc.buildbear.io/verify/sourcify/server/sanam"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
